package tools;

public class INfo 
{

    // JUST MADE A PACKAGE NAMED TOOLS AND INSERTED SOME FILES INTO IT.
    // IF YOU WANT TO USE THE CLASS FROM OUTSIDE THE FOLDER YOU WILL NEED TO IMPORT THE PACKAGE AND THEN IT COULD BE POSSIBLE ELSE IT WILL GIVE ERROR.
      // import tools.Calc
    // import tools.AdvCalc
}
